version: 2.1
orbs:
    cli: circleci/circleci-cli@0.1.9
executors:
    node:
        docker:
            - image: cimg/node:18.17.1
    python:
        docker:
            - image: python:3.11.4
commands:
    install_node_dependencies:
        description: Install dependencies
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v2-{{ checksum "package-lock.json" }}
            - run:
                  name: npm install
                  command: npm install
            - save_cache:
                  key: npm-cache-v2-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
                      - node_modules
    install_python_dependencies:
        description: Install poetry
        steps:
            - checkout
            - restore_cache:
                  keys: poetry-cache-v1-{{ checksum "poetry.lock" }}
            - run:
                  name: Create venv
                  command: python3 -m venv ~/.local/share/poetry
            - run:
                  name: Install pip and setuptools
                  command: ~/.local/share/poetry/bin/pip install -U pip setuptools
            - run:
                  name: Install poetry
                  command: ~/.local/share/poetry/bin/pip install poetry
            - run:
                  name: Link poetry (XXX hack)
                  command: ln -sv ~/.local/share/poetry/bin/poetry /usr/local/bin
            - run:
                  name: Install pip packages
                  command: poetry install --all-extras
            - save_cache:
                  key: poetry-cache-v1-{{ checksum "poetry.lock" }}
                  paths:
                      - ~/.local
                      - ~/.cache
jobs:
    svelte-check:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Generate type information
                  command: npm run sync-types
            - run:
                  name: Run svelte-check
                  command: npm run check:svelte-check
    eslint:
        executor: node
        parallelism: 8
        steps:
            - install_node_dependencies
            - run:
                  name: Generate type information
                  command: npm run sync-types
            - run:
                  name: Collect files to check
                  command: |
                      circleci tests glob "src/**/*.{ts,js,svelte}" | circleci tests split --split-by=timings > /tmp/files-to-check
            - store_artifacts:
                  path: /tmp/files-to-check
                  destination: files-checked
            - run:
                  name: Run eslint (split)
                  command: npm exec --package=eslint -- eslint $(cat /tmp/files-to-check)

    prettier:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Run prettier
                  command: npm run check:prettier:nocache
    knip:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Generate type information
                  command: npm run sync-types
            - run:
                  name: Run knip
                  command: npm run check:knip
    build:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Run build
                  command: npm run build
            - run:
                  name: Compress artifacts
                  command: tar --create --verbose --gzip --file=build.tar.gz build
            - store_artifacts:
                  path: build.tar.gz
    poetry_check:
        executor: python
        steps:
            - install_python_dependencies
            - run:
                  name: Poetry check
                  command: poetry check
    python_lint:
        executor: python
        steps:
            - install_python_dependencies
            - run:
                  name: Run flake8
                  command: poetry run flake8 bin/rename-component
    mypy:
        executor: python
        steps:
            - install_python_dependencies
            - run:
                  name: Run mypy
                  command: poetry run mypy bin/rename-component
workflows:
    test_all:
        jobs:
            - svelte-check
            - eslint
            - prettier
            - knip
            - build
            - poetry_check
            - python_lint
            - mypy
