version: 2.1
executors:
    node:
        docker:
            - image: cimg/node:19.6.0
    python:
        docker:
            - image: python:3.9.16
              environment:
                  PIPENV_PIPFILE: Pipfile-tools
commands:
    install_node_dependencies:
        description: Install dependencies
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - run:
                  name: npm ci
                  command: npm ci
    install_python_dependencies:
        description: Install pipenv
        steps:
            - checkout
            - restore_cache:
                  keys: cache-{{ checksum "Pipfile-tools.lock" }}
            - run:
                  name: Install pipenv
                  command: pip3 install pipenv
            - run:
                  name: Install pip packages
                  command: pipenv sync --dev
jobs:
    svelte-check:
        executor: node
        steps:
            - install_node_dependencies
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
            - run:
                  name: Run svelte-check
                  command: npm run check:svelte-check
    eslint:
        executor: node
        steps:
            - install_node_dependencies
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
            - run:
                  name: Generate type information
                  command: npm run sync-types
            - run:
                  name: Run eslint
                  command: npm run check:eslint
    prettier:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Run prettier
                  command: npm run check:prettier
    knip:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Run knip
                  command: npm run check:knip
    build:
        executor: node
        steps:
            - install_node_dependencies
            - run:
                  name: Run build
                  command: npm run build
    pipenv_check:
        executor: python
        steps:
            - install_python_dependencies
            - save_cache:
                  key: cache-{{ checksum "Pipfile-tools.lock" }}
                  paths:
                      - ~/.local
                      - ~/.cache
            - run:
                  name: Pipenv check
                  command: pipenv check
    python_lint:
        executor: python
        steps:
            - install_python_dependencies
            - run:
                  name: Run flake8
                  command: pipenv run flake8
    mypy:
        executor: python
        steps:
            - install_python_dependencies
            - run:
                  name: Run mypy
                  command: pipenv run mypy
workflows:
    test_all:
        jobs:
            - svelte-check
            - eslint
            - prettier
            - knip
            - build
            - pipenv_check
            - python_lint
            - mypy
